language: go
sudo: required

services:
    - docker

env:
    - CGO_ENABLED=0 GOOS=linux

script:
    - go build -a -tags netgo -ldflags '-w'
    - go test -a -tags netgo -ldflags '-w'
    - docker build -t billglover/load-sink .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push billglover/load-sink;
    fi

go:
    - 1.7
