language: go
sudo: required

services:
    - docker

script:
    - docker build -t billglover/load-sink .

go:
    - 1.7

gobuild_args: -a -tags netgo -ldflags '-w'

env:
    - CGO_ENABLED=0 GOOS=linux