language: go
sudo: required

services:
    - docker

script:
    - go build -a -tags netgo -ldflags '-w'
    - go test -a -tags netgo -ldflags '-w'
    - docker build -t billglover/load-sink .

go:
    - 1.7

env:
    - CGO_ENABLED=0 GOOS=linux