language: go
sudo: required

services:
    - docker

env:
    - CGO_ENABLED=0 GOOS=linux DOCKER_IMAGE_NAME=billglover/load-sink

install:
    - go get github.com/gorilla/mux

script:
    - go build -a -tags netgo -ldflags '-w'
    - go test -v -a -tags netgo -ldflags '-w' ./...
    - docker build -t $DOCKER_IMAGE_NAME .
    - if [ ! -z "$TRAVIS_TAG" ]; then 
        docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
      fi


after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "pushing container image $DOCKER_IMAGE_NAME";
        docker push $DOCKER_IMAGE_NAME;
      fi
    - if [ ! -z "$TRAVIS_TAG" ]; then
        echo "pushing container image $DOCKER_IMAGE_NAME:$TRAVIS_TAG";
        docker push $DOCKER_IMAGE_NAME:$TRAVIS_TAG; 
      fi

go:
    - 1.7
